services:
  dbs:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - dbs:/var/lib/postgresql/data
volumes:
  dbs:
    driver: local